utils::globalVariables(c(
    "limit",
    "URLencode",
    "conf",
    "get_scala_tweets_url",
    "is_secret_set",
    "last_fs_updates",
    "resp_header",
    "search_endpoint",
    "tail",
    "twitter_get"
))
